### ISSUE TITLE
Results after drop.na

### ISSUE THREAD

**Issue by zouwenjiao** [UBC-MDS/DSCI532_GROUP104_Movies#22]
I find that only 1 director has 4 movies in total, 1 director has 3 movies and there are lots of directors have 1 or 2 movies at most in the data frame.
So, shall we change the bar chart to top 50 rating/profit directors?

**Comment by flizhou** [comment]
I'm not sure what conditions you used to get the results. There are directors with more movies in some genres. I just uploaded the analysis worksheet. Feel free to play with the dataset there.

In the dataset, I plotted the top 30 directors instead of the top 50, since the bar chart becomes too big if we plot 50...

I'm not sure how we should handle directors with 1 or 2 movies. Maybe we just plot it and once we are comparing multiple directors it would look okay?

**Comment by sweber15** [comment]
My suggestion would be to just plot the data we have even if the directors have 1-2 movies. Tomorrow in lab if it looks bad, we can create a filters to better fit the data for all the charts.
